name: Automated tests on push

on:
  push:
    branches: [ "*" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: pmp_db_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build & run tests
        run: mvn -B clean verify -Dquarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/pmp_db_test -Dquarkus.datasource.username=postgres -Dquarkus.datasource.password=postgres